/**
 * Dados iniciais do cartão (antes em src/lib/data.ts).
 */
export const initialCardData = {
  id: 'default_card_1',
  template: 'default',
  fullName: 'João Silva',
  fullNameLink: '',
  jobTitle: 'Designer de Produto',
  jobTitleLink: '',
  bio: 'Especialista em criar experiências digitais centradas no usuário. 10+ anos transformando problemas complexos em interfaces simples e elegantes.',
  avatarUrl: 'https://images.unsplash.com/photo-1564564321837-a57b7070ac4f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  avatarLink: '',
  bannerUrl: 'https://images.unsplash.com/photo-1614680376593-902f74cf0d41?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
  bannerLink: '',
  vCardUrl: '#',
  isVerified: true,
  themeColor: '#5048e5',
  fontFamily: 'Inter',
  baseFontSize: 16,
  links: [
    { id: '1', type: 'whatsapp', label: 'WhatsApp', value: '5511999999999', icon: 'forum', color: '#25D366' },
    { id: '2', type: 'instagram', label: 'Instagram', value: 'joao.silva', icon: 'photo_camera', color: '#E1306C' },
    { id: '3', type: 'linkedin', label: 'LinkedIn', value: 'joao-silva', icon: 'work', color: '#0077b5' },
    { id: '4', type: 'website', label: 'Portfólio', value: 'https://joaosilva.design', icon: 'language', color: '#5048e5' },
  ],
  stats: [
    { label: 'Anos Exp.', value: '12', url: '' },
    { label: 'Projetos', value: '150+', url: '' },
    { label: 'Prêmios', value: '08', url: '' },
  ],
  saveContactLabel: 'Salvar Contato',
  qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=example',
  qrCodeData: '',
  customWebsiteUrl: 'www.digicard.studio/joaosilva',
  footerText: 'DESIGNED WITH DIGICARD STUDIO © 2024',
  physicalShowAvatar: true,
  physicalShowTitle: true,
  physicalShowStats: true,
  physicalShowLinks: true,
  physicalShowQR: true,
  physicalShowFooter: true,
  physicalShowCutMarks: false,
  physicalBackgroundColor: '#ffffff',
  lastUpdated: Date.now(),
};
